### ISSUE TITLE
Not a biggy

### ISSUE THREAD

**Issue by LorneBarnaby** [callumw123/Leninux#2]
https://github.com/callumw123/Leninux/blob/868f257a23e6dee21f1af48a61e6c2f9b647d4e4/Windows/downloader.py#L23

os.chmod is specific to unix and although is not called would cause error if was
https://docs.python.org/2/library/os.html

**Comment by social-anthrax** [comment]
It is actually for both. Windows python still uses os.chmod. Just tested and seems to work.

**Comment by LorneBarnaby** [comment]
sorry was looking at fchmod not chmod my bad
