### ISSUE TITLE
Might not break it but is wrong

### ISSUE THREAD

**Issue by LorneBarnaby** [callumw123/Leninux#4]
https://github.com/callumw123/Leninux/blob/26e87dedc1ead73c4a3824abd81958f79b356d1c/Ubuntu/SecurityFiles/CommonPassword#L28

minlen=10 is not required on pam deny as pam deny is only called when the password is wrong

**Comment by callumw123** [comment]
Thx I hadn’t noticed. I think it is still there from when we totally screwed the password policy up. I’ll delete it.
